### ISSUE TITLE
A method for getting the exchange rate.

### ISSUE THREAD

**Issue by entee28** [suchlab/currenzy#1]
Just a suggestion, might we have a method where you just want to get the exchange rate from the base currency to the target currency?

**Comment by itaibo** [comment]
You could use the conversion made for 1 monetary unit. That would return the exchange rate.

For example, to know the exchange rate for the USD having EUR as base:

```js
import Currenzy from 'currenzy';

const currenzy = new Currenzy('EUR');
const USD_conversion_rate = await currenzy.convert(1, 'USD');
```
